version: '3.1'

services:
  postgres:
    image: postgres:latest
    container_name : pg.learning_services
    restart: always
    ports:
      - 5432:5432
    networks: 
      - learning
    environment:
      POSTGRES_USER : learningservice
      POSTGRES_PASSWORD: learningservice
      POSTGRES_DB : db.learning_services
    volumes:
     - ./data:/var/lib/postgresql/data

networks:
  learning:
